# Generated by Django 5.2.8 on 2025-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expenses_type', models.CharField(choices=[('rent', 'Rent'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment')])),
                ('amount', models.CharField()),
                ('note', models.CharField(blank=True, null=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
